# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d93556e8632ce53593528a8f5d24230b4358682995364fdde0bc1498fa307ae98bc816b759d6405a83d83f4eaee5e4043a7de5947886a12b9748361a34c2422f

test:
  secret_key_base: 78d95ae18900117b1bb7086d4ac29eb8e78cc2eb17e09011ec838327a41b103acad1981ee3faa9babf81cd6453791fcb2d6e36f0b0514be68ce183eafc3f6e06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
